// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn super_sub_test_1() {
    let original = r##"^This is super^ ~This is sub~
"##;
    let expected = r##"<p><sup>This is super</sup> <sub>This is sub</sub></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_2() {
    let original = r##"~This is stricken out~
"##;
    let expected = r##"<p><sub>This is stricken out</sub></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_3() {
    let original = r##"~This is \~stricken~
"##;
    let expected = r##"<p><sub>This is ~stricken</sub></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_4() {
    let original = r##"~This~is~nothing~
"##;
    let expected = r##"<p><sub>This</sub>is<sub>nothing</sub></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_5() {
    let original = r##"~This ~~is not stricken.~
"##;
    let expected = r##"<p><sub>This ~~is not stricken.</sub></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_6() {
    let original = r##"~~This ~is~~ stricken.~
"##;
    let expected = r##"<p><del>This ~is</del> stricken.~</p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_7() {
    let original = r##"~This ~~is stricken~ but this is not~~
"##;
    let expected = r##"<p><sub>This ~~is stricken</sub> but this is not~~</p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_8() {
    let original = r##"H~2~O

y=x^2^a+xb+c
"##;
    let expected = r##"<p>H<sub>2</sub>O</p>
<p>y=x<sup>2</sup>a+xb+c</p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_9() {
    let original = r##"~foo~~

^bar^^
"##;
    let expected = r##"<p>~foo~~</p>
<p>^bar^^</p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_10() {
    let original = r##"~foo^~^bar~

*foo_*_bar*
"##;
    let expected = r##"<p><sub>foo^</sub>^bar~</p>
<p><em>foo_</em>_bar*</p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn rrrr() {
    let original = r##"Shinseki Frieren • Cre: @최최
"##;
    let expected = r##"
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn qqqqqqqqqqq() {
    let original = r##">Open-source slicing has always been built on a tradition of collaboration and attribution. Slic3r, created by Alessandro Ranellucci and the RepRap community, laid the foundation. PrusaSlicer by Prusa Research built on Slic3r and acknowledged that heritage. Bambu Studio in turn forked from PrusaSlicer, and SuperSlicer by @supermerill extended PrusaSlicer with community-driven enhancements. Each project carried the work of its predecessors forward, crediting those who came before.\n>\n>OrcaSlicer began in that same spirit, drawing from BambuStudio, PrusaSlicer, and ideas inspired by CuraSlicer and SuperSlicer.\n\n[Source](https://github.com/OrcaSlicer/orcaslicer)
"##;
    let expected = r##"
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn wwwwwwwwwwwww() {
    let original = r##"This is !super@this.is.sub
"##;
    let expected = r##"<p>This is <a href="//c/super@this.is.sub">super@this.is.sub</a></p>
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn hhhhhhhhh() {
    let original = r##"This is @super@this.is.sub
"##;
    let expected = r##"<p>This is <a href="//u/super@this.is.sub">super@this.is.sub</a></p>
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn hhhhhhhhhh() {
    let original = r##"This is http://this.is.sub
"##;
    let expected = r##"<p>This is <a href="http://this.is.sub">http://this.is.sub</a>
</p>
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn sssssssssssssssss() {
    let original = r##"This is http://this.is.sub
"##;
    let expected = r##"<p>This is <a href="http://this.is.sub">http://this.is.sub</a></p>
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn tttttttt() {
    let original = r##"This is http://this.is.sub yay!
"##;
    let expected = r##"<p>This is <a href="http://this.is.sub">http://this.is.sub</a>yay!</p>
"##;
    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_11() {
    let original = r##"H^+^ + OH^-^
"##;
    let expected = r##"<p>H<sup>+</sup> + OH<sup>-</sup></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_12() {
    let original = r##"Ca^2+^ + CO~3~^2-^
"##;
    let expected = r##"<p>Ca<sup>2+</sup> + CO<sub>3</sub><sup>2-</sup></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_13() {
    let original = r##"NH~4~^+^
"##;
    let expected = r##"<p>NH<sub>4</sub><sup>+</sup></p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}

#[test]
fn super_sub_test_14() {
    let original = r##"^+^ not superscript
"##;
    let expected = r##"<p>^+^ not superscript</p>
"##;

    test_markdown_html(
        original, expected, false, false, false, true, false, false, false,
    );
}
